#!/usr/bin/env python3
"""Regenerate evidence/INDEX.md from the manifests under evidence/.

One row per acceptance record, newest validation first. The table is derived from the
manifests, so it cannot disagree with them; run this after filing a record.

    correctness/index_evidence.py            # rewrite evidence/INDEX.md
    correctness/index_evidence.py --check    # exit 1 if INDEX.md is stale
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import List, Optional

REPO_ROOT = Path(__file__).resolve().parent.parent
EVIDENCE_DIR = REPO_ROOT / "evidence"

HEADER = [
    "# Acceptance records — index",
    "",
    "Generated by `correctness/index_evidence.py` — do not edit by hand.",
    "",
    "| Product | Version | Cases | Result | Security | Validated | Class |",
    "|---|---|---|---|---|---|---|",
]


def rows(evidence_dir: Path) -> List[str]:
    entries = []
    for path in sorted(evidence_dir.glob("*/*/manifest.json")):
        manifest = json.loads(path.read_text())
        product, version = path.parent.parent.name, path.parent.name
        cases = manifest.get("cases") or []
        passed = sum(1 for c in cases if (c.get("result") or {}).get("status") == "PASS")
        entries.append((
            manifest.get("timestamp", ""),
            "| [%s](%s/%s/) | `%s` | %d (%d passed) | **%s** | %s | %s | %s |" % (
                product, product, version, version, len(cases), passed,
                manifest.get("result"), (manifest.get("security") or {}).get("status"),
                manifest.get("timestamp", "")[:10], manifest.get("evidence_class"))))
    entries.sort(key=lambda e: e[0], reverse=True)
    return [line for _, line in entries] or ["| _(none yet)_ | | | | | | |"]


def render(evidence_dir: Optional[Path] = None) -> str:
    return "\n".join(HEADER + rows(evidence_dir or EVIDENCE_DIR)) + "\n"


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(description="Regenerate evidence/INDEX.md.")
    parser.add_argument("--check", action="store_true",
                        help="do not write; exit 1 if INDEX.md differs from the manifests")
    args = parser.parse_args(argv)
    index = EVIDENCE_DIR / "INDEX.md"
    text = render()
    if args.check:
        current = index.read_text() if index.is_file() else ""
        if current != text:
            print("index_evidence: %s is stale; run correctness/index_evidence.py" % index,
                  file=sys.stderr)
            return 1
        return 0
    index.write_text(text)
    print("index_evidence: wrote %s" % index, file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
