#!/usr/bin/env python3
"""Regenerate evidence/INDEX.md and evidence/index.json from the manifests under evidence/.

One entry per acceptance record, newest validation first. Both files are derived from
the manifests, so they cannot disagree with them; run this after filing a record.

INDEX.md is for a reader of this repository. index.json is for a machine: the
SciRecast website reads it to show what has been validated (decision D9 in
docs/CORRECTNESS-ORGANIZATION.md). It carries the fields a listing needs and nothing
generated at write time, so two runs over the same records produce the same bytes and
`--check` can compare them.

    correctness/index_evidence.py            # rewrite both files
    correctness/index_evidence.py --check    # exit 1 if either is stale
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Dict, List, Optional, Tuple

REPO_ROOT = Path(__file__).resolve().parent.parent
EVIDENCE_DIR = REPO_ROOT / "evidence"

INDEX_SCHEMA = 1

HEADER = [
    "# Acceptance records — index",
    "",
    "Generated by `correctness/index_evidence.py` — do not edit by hand. "
    "`index.json` beside this file holds the same entries for machines.",
    "",
    "| Product | Version | Cases | Result | Security | Validated | Class |",
    "|---|---|---|---|---|---|---|",
]


def entries(evidence_dir: Path) -> List[Dict[str, object]]:
    """One entry per manifest, newest validation first."""
    found: List[Tuple[str, Dict[str, object]]] = []
    for path in sorted(evidence_dir.glob("*/*/manifest.json")):
        manifest = json.loads(path.read_text())
        product, version = path.parent.parent.name, path.parent.name
        cases = manifest.get("cases") or []
        artifact = manifest.get("artifact") or {}
        reference = manifest.get("reference") or {}
        entry: Dict[str, object] = {
            "product": product,
            "version": version,
            "path": "%s/%s/" % (product, version),
            "artifact": {
                "name": artifact.get("name"),
                "repo": artifact.get("repo"),
                "commit": artifact.get("commit"),
            },
            "reference": {
                "model": reference.get("model"),
                "commit_or_tag": reference.get("commit_or_tag"),
            },
            "cases": {
                "total": len(cases),
                "passed": sum(1 for c in cases
                              if (c.get("result") or {}).get("status") == "PASS"),
                "ids": [c.get("id") for c in cases],
            },
            "result": manifest.get("result"),
            "security": (manifest.get("security") or {}).get("status"),
            "evidence_class": manifest.get("evidence_class"),
            "validated": manifest.get("timestamp"),
            "cc_test_commit": (manifest.get("cc_test") or {}).get("commit"),
        }
        found.append((str(manifest.get("timestamp", "")), entry))
    found.sort(key=lambda item: item[0], reverse=True)
    return [entry for _, entry in found]


def render_markdown(evidence_dir: Optional[Path] = None) -> str:
    rows = []
    for e in entries(evidence_dir or EVIDENCE_DIR):
        cases = e["cases"]
        assert isinstance(cases, dict)
        rows.append("| [%s](%s) | `%s` | %d (%d passed) | **%s** | %s | %s | %s |" % (
            e["product"], e["path"], e["version"], cases["total"], cases["passed"],
            e["result"], e["security"], str(e["validated"])[:10], e["evidence_class"]))
    return "\n".join(HEADER + (rows or ["| _(none yet)_ | | | | | | |"])) + "\n"


def render_json(evidence_dir: Optional[Path] = None) -> str:
    document = {
        "schema": INDEX_SCHEMA,
        "source": "evidence/<product>/<version>/manifest.json, via correctness/index_evidence.py",
        "records": entries(evidence_dir or EVIDENCE_DIR),
    }
    return json.dumps(document, indent=2) + "\n"


# The first version rendered the table only; callers of that name still work.
render = render_markdown


def main(argv: Optional[List[str]] = None) -> int:
    parser = argparse.ArgumentParser(
        description="Regenerate evidence/INDEX.md and evidence/index.json.")
    parser.add_argument("--check", action="store_true",
                        help="do not write; exit 1 if either file differs from the manifests")
    args = parser.parse_args(argv)
    outputs = {
        EVIDENCE_DIR / "INDEX.md": render_markdown(),
        EVIDENCE_DIR / "index.json": render_json(),
    }
    if args.check:
        stale = [path for path, text in outputs.items()
                 if not path.is_file() or path.read_text() != text]
        for path in stale:
            print("index_evidence: %s is stale; run correctness/index_evidence.py" % path,
                  file=sys.stderr)
        return 1 if stale else 0
    for path, text in outputs.items():
        path.write_text(text)
        print("index_evidence: wrote %s" % path, file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
